# Generated by Django 6.0.5 on 2026-05-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='Без породы', max_length=100, verbose_name='Порода'),
        ),
    ]
