# Generated by Django 6.0.5 on 2026-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets_images/', verbose_name='Фото питомца'),
        ),
    ]
