# Generated by Django 6.0.5 on 2026-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=15, verbose_name='Количество на складе'),
        ),
    ]
