# Generated by Django 6.0.5 on 2026-05-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review_admin_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В обработке'), ('cancel_requested', 'Запрос на отмену ⚠️'), ('completed', 'Выполнен ✅'), ('cancelled', 'Отменен ❌')], default='in_progress', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
