# Generated by Django 6.0.5 on 2026-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('changed_mind', 'Передумал(а) покупать'), ('found_cheaper', 'Нашел(ла) дешевле в другом месте'), ('long_delivery', 'Не устраивают сроки доставки'), ('ordered_by_mistake', 'Ошибся(лась) при оформлении заказа'), ('other', 'Другая причина')], max_length=50, null=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason_text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к отмене'),
        ),
    ]
