# Generated by Django 6.0.5 on 2026-05-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_customuser_address_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_gallery_images', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.CreateModel(
            name='GalleryImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_comments', to='store.imagegallery', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Комментарий к фото галереи',
                'verbose_name_plural': 'Комментарии к фото галереи',
                'ordering': ['-created_at'],
            },
        ),
    ]
