# Generated by Django 6.0.5 on 2026-05-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_imagegallery_likes_galleryimagecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='store.pet', verbose_name='Питомец (опционально)'),
        ),
    ]
